import os


def _validate(path: str) -> int:
    with open(path, "r", encoding="utf-8") as f:
        head = "".join([next(f) for _ in range(8)])
    if "autogenerated by pip-compile" not in head:
        print(f"missing pip-compile header: {path}")
        return 1
    if "--pip-args='--python-version 3.11'" not in head:
        print(f"missing python 3.11 resolver args in header: {path}")
        return 1
    return 0


def main() -> int:
    base = os.path.dirname(os.path.dirname(__file__))
    a = os.path.join(base, "requirements.txt")
    b = os.path.join(base, "requirements-dev.txt")
    return _validate(a) or _validate(b)


if __name__ == "__main__":
    raise SystemExit(main())

