"""ai_and_system_updates

Revision ID: 862a475c39d0
Revises: 0003_celery_dead_letters
Create Date: 2026-04-13 07:23:11.234193

"""

from alembic import op
import sqlalchemy as sa


revision = '862a475c39d0'
down_revision = '0003_celery_dead_letters'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cj_raw_products')
    op.alter_column('candidate_products', 'source_platform',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'1688'::text"))
    op.alter_column('candidate_products', 'source_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('candidate_products', 'backup_source_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('candidate_products', 'discovery_evidence',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('candidate_products', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('candidate_products', 'market_comparison_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('candidate_products', 'supplier_info',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('candidate_products', 'origin_video_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('candidate_products', 'visual_fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_candidate_variants_raw'), table_name='candidate_products', postgresql_using='gin')
    op.create_index(op.f('ix_candidate_products_source_platform'), 'candidate_products', ['source_platform'], unique=False)
    op.create_index(op.f('ix_candidate_products_visual_fingerprint'), 'candidate_products', ['visual_fingerprint'], unique=False)
    op.create_index(op.f('ix_orders_referrer_id'), 'orders', ['referrer_id'], unique=False)
    op.drop_index(op.f('ix_point_transactions_order_id'), table_name='point_transactions')
    op.alter_column('products', 'titles',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'descriptions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'source_platform',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'1688'::text"))
    op.alter_column('products', 'source_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'backup_source_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('products', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'variants',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'certificate_images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'metafields',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'visual_fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('idx_product_detail_images', 'products', ['detail_images'], unique=False, postgresql_using='gin')
    op.create_index('idx_product_metafields', 'products', ['metafields'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_products_source_platform'), 'products', ['source_platform'], unique=False)
    op.create_index(op.f('ix_products_visual_fingerprint'), 'products', ['visual_fingerprint'], unique=False)
    op.drop_column('products', 'media')
    op.alter_column('renewal_cards', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('renewal_cards', 'plan_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_renewal_cards_id'), 'renewal_cards', ['id'], unique=False)
    op.drop_constraint(op.f('renewal_cards_plan_id_fkey'), 'renewal_cards', type_='foreignkey')
    op.drop_column('renewal_cards', 'revoked_at')
    op.alter_column('suppliers', 'qualifications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('suppliers', 'custom_capability',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users_ext', 'kol_apply_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_ext_backup_email'), 'users_ext', ['backup_email'], unique=False)
    op.alter_column('wallet_transactions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_transactions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_ext_backup_email'), table_name='users_ext')
    op.alter_column('users_ext', 'kol_apply_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('suppliers', 'custom_capability',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('suppliers', 'qualifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('renewal_cards', sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('renewal_cards_plan_id_fkey'), 'renewal_cards', 'checkin_plans', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_renewal_cards_id'), table_name='renewal_cards')
    op.alter_column('renewal_cards', 'plan_id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('renewal_cards', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('products', sa.Column('media', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_visual_fingerprint'), table_name='products')
    op.drop_index(op.f('ix_products_source_platform'), table_name='products')
    op.drop_index('idx_product_metafields', table_name='products', postgresql_using='gin')
    op.drop_index('idx_product_detail_images', table_name='products', postgresql_using='gin')
    op.alter_column('products', 'visual_fingerprint',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'metafields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'certificate_images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'variants',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'backup_source_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'source_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('products', 'source_platform',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'1688'::text"))
    op.alter_column('products', 'descriptions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'titles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_point_transactions_order_id'), 'point_transactions', ['order_id'], unique=False)
    op.drop_index(op.f('ix_orders_referrer_id'), table_name='orders')
    op.drop_index(op.f('ix_candidate_products_visual_fingerprint'), table_name='candidate_products')
    op.drop_index(op.f('ix_candidate_products_source_platform'), table_name='candidate_products')
    op.create_index(op.f('idx_candidate_variants_raw'), 'candidate_products', ['variants_raw'], unique=False, postgresql_using='gin')
    op.alter_column('candidate_products', 'visual_fingerprint',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidate_products', 'origin_video_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidate_products', 'supplier_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('candidate_products', 'market_comparison_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidate_products', 'images',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('candidate_products', 'discovery_evidence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('candidate_products', 'backup_source_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidate_products', 'source_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('candidate_products', 'source_platform',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'1688'::text"))
    op.create_table('cj_raw_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cj_pid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('title_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('market_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('market_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_compare_at_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('freight_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('inventory_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vendor_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shipping_days', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cj_raw_products_pkey')),
    sa.UniqueConstraint('cj_pid', name=op.f('cj_raw_products_cj_pid_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###

